### PR TITLE
Clarify information regarding ref. to web pages

### PR DESCRIPTION
**Pull request by ljgarcia**
Chagelog:
* Add more information regarding the citation of web pages (included as links in the text but also added to the references)
* Having them as links makes it easier to navigate to those pages from the text, having them as references makes it easier to credit autohrs/owners and do text-mining on them

### CODE REVIEW

**Comment by ktym** [comment]
What's the "datates"? databases maybe?

**Review by inutano — APPROVED** [review]
made a commit to fix the typo, revert if it's not

**Comment by ljgarcia** [comment]
@ktym I mean data in general. It could be a database, a CSV, or any other format reporting data. For instance, if you are citing a PubAnnotation repo, that is data, and authors and so should be identified together with the version (if possible).

**Comment by ktym** [comment]
Thanks, I just wanted to clarify the term which I could not find in my dictionary.

**Pull request merged**
